name: ATVLoadly
version: "1.0.5"
slug: atvloadly
description: Apple TV sideload server
url: "https://github.com/trsaid/ha-atvloadly"

startup: services
boot: auto

init: false

arch:
  - aarch64
  - armv7
  - amd64

host_network: true
host_dbus: true

privileged:
  - SYS_ADMIN

map:
  - config:rw

environment:
  SERVICE_PORT: "5533"

options: {}
schema: {}