name: ATVLoadly
version: "1.0.1"
slug: atvloadly
description: Apple TV sideload server
url: "https://github.com/trsaid/ha-atvloadly"

startup: services
boot: auto
init: false

arch:
  - aarch64
  - armv7
  - amd64

ingress: true
ingress_port: 80

panel_icon: mdi:apple

host_network: true
host_dbus: true

privileged:
  - SYS_ADMIN

map:
  - config:rw

options: {}
schema: {}

ports:
  5533/tcp: 5533